using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）RinsPendantTreasure — projection (weakened) copy of RinsPendantTreasure.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionRinsPendantTreasure : ProjectionCardBase
{
    public ProjectionRinsPendantTreasure() : base(CardType.Skill, CardRarity.Rare, TargetType.None) { }

    // 王之财宝！ referenced in the description — show a card preview on hover.
    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
        new[] { HoverTipFactory.FromCard<KingTreasure>() };

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "RinsPendantTreasure.png".CardPortraitPath();
    public override string CustomPortraitPath => "RinsPendantTreasure.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "RinsPendantTreasure.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        for (int i = 0; i < 2; i++)
            await KingTreasure.AddToHand(Owner);
    }
    protected override void OnUpgrade() { }
}
