using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Powers;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）RinsPendantPioneer — projection (weakened) copy of RinsPendantPioneer.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionRinsPendantPioneer : ProjectionCardBase
{
    public ProjectionRinsPendantPioneer() : base(CardType.Skill, CardRarity.Rare, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "RinsPendantPioneer.png".CardPortraitPath();
    public override string CustomPortraitPath => "RinsPendantPioneer.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "RinsPendantPioneer.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await PowerCmd.Apply<RinsPendantPioneerPower>(
            choiceContext, Owner.Creature, 1m, Owner.Creature, this);
    }
    protected override void OnUpgrade() { }
}
