using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）ProjectionBegin — projection (weakened) copy of ProjectionBegin.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionProjectionBegin : ProjectionCardBase
{
    public ProjectionProjectionBegin() : base(CardType.Attack, CardRarity.Common, TargetType.AnyEnemy) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        new DamageVar(4m, ValueProp.Move)
    };
    public override string PortraitPath => "ProjectionBegin.png".CardPortraitPath();
    public override string CustomPortraitPath => "ProjectionBegin.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "ProjectionBegin.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        // Pure damage — no projection card is generated.
        ArgumentNullException.ThrowIfNull(cardPlay.Target, nameof(cardPlay.Target));
        await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
            .FromCard(this)
            .Targeting(cardPlay.Target)
            .Execute(choiceContext);
    }
    protected override void OnUpgrade()
    {
    }
}
