using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）MagicGemWind — projection (weakened) copy of MagicGemWind.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionMagicGemWind : ProjectionCardBase
{
    public ProjectionMagicGemWind() : base(CardType.Skill, CardRarity.Common, TargetType.Self) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "MagicGemWind.png".CardPortraitPath();
    public override string CustomPortraitPath => "MagicGemWind.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "MagicGemWind.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await CreatureCmd.Heal(Owner.Creature, 4m);
    }
    protected override void OnUpgrade()
    {
    }
}
