using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）PassTheParcel — projection (weakened) copy of PassTheParcel.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionPassTheParcel : ProjectionCardBase
{
    public ProjectionPassTheParcel() : base(CardType.Skill, CardRarity.Uncommon, TargetType.AnyEnemy) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        // No canonical vars
    };
    public override string PortraitPath => "PassTheParcel.png".CardPortraitPath();
    public override string CustomPortraitPath => "PassTheParcel.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "PassTheParcel.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        ArgumentNullException.ThrowIfNull(cardPlay.Target);
        await FateNightOfTheGalacticRailway.Core.Powers.PassTheParcel.ApplyMark(
            choiceContext, cardPlay.Target, Owner.Creature, this, 4m);
    }
    protected override void OnUpgrade()
    {
    }
}
