using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）HumanWeave — projection (weakened) copy of HumanWeave.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionHumanWeave : ProjectionCardBase
{
    public ProjectionHumanWeave() : base(CardType.Skill, CardRarity.Event, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "HumanWeave.png".CardPortraitPath();
    public override string CustomPortraitPath => "HumanWeave.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "HumanWeave.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await CreatureCmd.Heal(Owner.Creature, 3m);
        await CardPileCmd.Draw(choiceContext, 1m, Owner);
    }
    protected override void OnUpgrade() { }
}
