using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）FantasyCollapse — projection (weakened) copy of FantasyCollapse.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionFantasyCollapse : ProjectionCardBase
{
    public ProjectionFantasyCollapse() : base(CardType.Attack, CardRarity.Uncommon, TargetType.AllEnemies) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        new DamageVar(4m, ValueProp.Move)
    };
    public override string PortraitPath => "FantasyCollapse.png".CardPortraitPath();
    public override string CustomPortraitPath => "FantasyCollapse.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "FantasyCollapse.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        // Simple AOE — does not return to hand and has no cost-reduction hook.
        await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
            .FromCard(this)
            .TargetingAllOpponents(base.CombatState!)
            .Execute(choiceContext);
    }
    protected override void OnUpgrade()
    {
    }
}
