using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）KingTreasure — projection (weakened) copy of KingTreasure.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionKingTreasure : ProjectionCardBase
{
    public ProjectionKingTreasure() : base(CardType.Attack, CardRarity.Event, TargetType.AllEnemies) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        new DamageVar(3m, ValueProp.Move)
    };
    public override string PortraitPath => "KingTreasure.png".CardPortraitPath();
    public override string CustomPortraitPath => "KingTreasure.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "KingTreasure.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
            .FromCard(this)
            .TargetingAllOpponents(base.CombatState!)
            .Execute(choiceContext);
    }
    protected override void OnUpgrade()
    {
        base.DynamicVars.Damage.UpgradeValueBy(3m);
    }
    /// <summary>
    /// Add a KingTreasure to hand. If one already exists, upgrade it (+3 dmg)
    /// instead of adding a duplicate. Uses CardCmd.Upgrade for proper UI refresh.
    /// </summary>
    public static async Task AddToHand(Player owner)
    {
        var state = owner.Creature.CombatState;
        if (state == null) return;

        // Re-query hand each call — essential for sequential batch generation
        var existing = PileType.Hand.GetPile(owner)?.Cards.OfType<KingTreasure>().FirstOrDefault();
        if (existing != null)
        {
            existing.DynamicVars.Damage.UpgradeValueBy(3m);
        }
        else
        {
            var card = state.CreateCard<KingTreasure>(owner);
            await CardPileCmd.AddGeneratedCardToCombat(card, PileType.Hand, owner);
        }
    }
}
