using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）ManaBurst — projection (weakened) copy of ManaBurst.
/// Fixed flat AOE — no cost-reduction scaling.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionManaBurst : ProjectionCardBase
{
    public ProjectionManaBurst() : base(CardType.Attack, CardRarity.Rare, TargetType.AllEnemies) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        new DamageVar(10m, ValueProp.Move)
    };
    public override string PortraitPath => "ManaBurst.png".CardPortraitPath();
    public override string CustomPortraitPath => "ManaBurst.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "ManaBurst.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
            .FromCard(this)
            .TargetingAllOpponents(base.CombatState!)
            .Execute(choiceContext);
    }
    protected override void OnUpgrade()
    {
    }
}
