using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）OpenLock — projection (weakened) copy of OpenLock.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionOpenLock : ProjectionCardBase
{
    public ProjectionOpenLock() : base(CardType.Skill, CardRarity.Rare, TargetType.None) { }

    // 王之财宝！ referenced in the description — show a card preview on hover.
    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
        new[] { HoverTipFactory.FromCard<KingTreasure>() };

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "OpenLock.png".CardPortraitPath();
    public override string CustomPortraitPath => "OpenLock.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "OpenLock.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        if (Owner == null) return;
        // Only creates a King's Treasure — no random Rin Skill card.
        await KingTreasure.AddToHand(Owner);
    }
    protected override void OnUpgrade() { }
}
