using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）SimpleTrial — projection (weakened) copy of SimpleTrial.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionSimpleTrial : ProjectionCardBase
{
    public ProjectionSimpleTrial() : base(CardType.Skill, CardRarity.Uncommon, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        // No canonical vars
    };
    public override string PortraitPath => "SimpleTrial.png".CardPortraitPath();
    public override string CustomPortraitPath => "SimpleTrial.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "SimpleTrial.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        if (Owner == null) return;
        // 50% chance to gain 1 Energy.
        if (Owner.RunState.Rng.CombatCardSelection.NextDouble() < 0.5)
            await PlayerCmd.GainEnergy(1m, Owner);
    }
    protected override void OnUpgrade()
    {
    }
}
