using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）AhaSweep — projection (weakened) copy of AhaSweep.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionAhaSweep : ProjectionCardBase
{
    public ProjectionAhaSweep() : base(CardType.Attack, CardRarity.Uncommon, TargetType.AllEnemies) { }

    // 阿哈打击！ referenced in the description — show a card preview on hover.
    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
        new[] { HoverTipFactory.FromCard<AhaStrike>() };

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        new DamageVar(1m, ValueProp.Move)
    };
    public override string PortraitPath => "AhaSweep.png".CardPortraitPath();
    public override string CustomPortraitPath => "AhaSweep.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "AhaSweep.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
            .FromCard(this)
            .TargetingAllOpponents(base.CombatState!)
            .Execute(choiceContext);

        // Create 1 Exhausting AhaStrike copy
        var strike = base.CombatState!.CreateCard<AhaStrike>(Owner);
        strike.AddKeyword(CardKeyword.Exhaust);
        await CardPileCmd.AddGeneratedCardToCombat(strike, PileType.Hand, Owner);
    }
    protected override void OnUpgrade()
    {
    }
}
