using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）FriendshipProof — projection (weakened) copy of FriendshipProof.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionFriendshipProof : ProjectionCardBase
{
    public ProjectionFriendshipProof() : base(CardType.Skill, CardRarity.Uncommon, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
    };
    public override string PortraitPath => "FriendshipProof.png".CardPortraitPath();
    public override string CustomPortraitPath => "FriendshipProof.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "FriendshipProof.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        // Simplified: just draw 1 card (no coin-flip loop).
        await CardPileCmd.Draw(choiceContext, 1m, Owner);
    }
    protected override void OnUpgrade()
    {
    }
}
