using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）RinsPendantProjection — projection (weakened) copy of RinsPendantProjection.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionRinsPendantProjection : ProjectionCardBase
{
    public ProjectionRinsPendantProjection() : base(CardType.Skill, CardRarity.Rare, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "RinsPendantProjection.png".CardPortraitPath();
    public override string CustomPortraitPath => "RinsPendantProjection.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "RinsPendantProjection.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        // Draw 1 — the drawn card is not made free.
        await CardPileCmd.Draw(choiceContext, 1m, Owner);
    }
    protected override void OnUpgrade()
    {
    }
}
