using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Powers;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）MagicGemWater — projection (weakened) copy of MagicGemWater.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionMagicGemWater : ProjectionCardBase
{
    public ProjectionMagicGemWater() : base(CardType.Skill, CardRarity.Common, TargetType.AnyEnemy) { }

    private decimal _extraDamage = 2m;
    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "MagicGemWater.png".CardPortraitPath();
    public override string CustomPortraitPath => "MagicGemWater.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "MagicGemWater.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        ArgumentNullException.ThrowIfNull(cardPlay.Target);
        await PowerCmd.Apply<RuleBreakerMark>(choiceContext, cardPlay.Target, _extraDamage, Owner.Creature, this);
    }
    protected override void OnUpgrade()
    {
        _extraDamage = 3m;
    }
}
