using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）WhyAreYouHere — projection (weakened) copy of WhyAreYouHere.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionWhyAreYouHere : ProjectionCardBase
{
    public ProjectionWhyAreYouHere() : base(CardType.Power, CardRarity.Rare, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        // No canonical vars
    };
    public override string PortraitPath => "WhyAreYouHere.png".CardPortraitPath();
    public override string CustomPortraitPath => "WhyAreYouHere.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "WhyAreYouHere.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await PowerCmd.Apply<FateNightOfTheGalacticRailway.Core.Powers.WhyAreYouHere>(choiceContext, Owner.Creature, 1m, Owner.Creature, this);
    }
    protected override void OnUpgrade()
    {
    }
}
