using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）Avalon — projection (weakened) copy of Avalon.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionAvalon : ProjectionCardBase
{
    public ProjectionAvalon() : base(CardType.Power, CardRarity.Rare, TargetType.Self) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        // No canonical vars
    };
    public override string PortraitPath => "Avalon.png".CardPortraitPath();
    public override string CustomPortraitPath => "Avalon.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "Avalon.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        // Pure heal — no regen power is granted.
        await CreatureCmd.Heal(Owner.Creature, 10m);
    }
    protected override void OnUpgrade()
    {
    }
}
