using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.CardSelection;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）DeathTitanCloak — projection (weakened) copy of DeathTitanCloak.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionDeathTitanCloak : ProjectionCardBase
{
    public ProjectionDeathTitanCloak() : base(CardType.Skill, CardRarity.Uncommon, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "DeathTitanCloak.png".CardPortraitPath();
    public override string CustomPortraitPath => "DeathTitanCloak.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "DeathTitanCloak.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        if (Owner == null) return;

        var drawPile = PileType.Draw.GetPile(Owner);
        if (drawPile == null || drawPile.Cards.Count == 0) return;

        var candidates = await CardSelectCmd.FromCombatPile(
            choiceContext, drawPile, Owner,
            new CardSelectorPrefs(CardSelectorPrefs.RemoveSelectionPrompt, 1));

        foreach (var card in candidates)
            await CardCmd.Exhaust(choiceContext, card);

        await CardPileCmd.Draw(choiceContext, 1m, Owner);
    }
    protected override void OnUpgrade() { }
}
