using System;
using System.Collections.Generic;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>Maps each original card type to its projection card type.
/// Cards without a projection map to the generic 伪卡牌.</summary>
public static class ProjectionRegistry
{
    private static readonly Dictionary<Type, Type> _map = new()
    {
        [typeof(AhaMirror)] = typeof(ProjectionAhaMirror),
        [typeof(AhaStrike)] = typeof(ProjectionAhaStrike),
        [typeof(AhaSupport)] = typeof(ProjectionAhaSupport),
        [typeof(AhaSweep)] = typeof(ProjectionAhaSweep),
        [typeof(AhaSword)] = typeof(ProjectionAhaSword),
        [typeof(Avalon)] = typeof(ProjectionAvalon),
        [typeof(Boring)] = typeof(ProjectionBoring),
        [typeof(Cooperation)] = typeof(ProjectionCooperation),
        [typeof(CraneWingThree)] = typeof(ProjectionCraneWingThree),
        [typeof(DeathTitanCloak)] = typeof(ProjectionDeathTitanCloak),
        [typeof(DivineCreation)] = typeof(ProjectionDivineCreation),
        [typeof(EpicClayTablet)] = typeof(ProjectionEpicClayTablet),
        [typeof(FakeBook)] = typeof(ProjectionFakeBook),
        [typeof(FantasyCollapse)] = typeof(ProjectionFantasyCollapse),
        [typeof(FriendshipProof)] = typeof(ProjectionFriendshipProof),
        [typeof(FullAttack)] = typeof(ProjectionFullAttack),
        [typeof(GaeBolg)] = typeof(ProjectionGaeBolg),
        [typeof(GoldenRule)] = typeof(ProjectionGoldenRule),
        [typeof(GoldenSlash1)] = typeof(ProjectionGoldenSlash1),
        [typeof(GoldenSlash2)] = typeof(ProjectionGoldenSlash2),
        [typeof(GoldenSlash3)] = typeof(ProjectionGoldenSlash3),
        [typeof(HumanWeave)] = typeof(ProjectionHumanWeave),
        [typeof(KingGoblet)] = typeof(ProjectionKingGoblet),
        [typeof(KingTreasure)] = typeof(ProjectionKingTreasure),
        [typeof(KingWine)] = typeof(ProjectionKingWine),
        [typeof(LawAka)] = typeof(ProjectionLawAka),
        [typeof(MagicGemEarth)] = typeof(ProjectionMagicGemEarth),
        [typeof(MagicGemFire)] = typeof(ProjectionMagicGemFire),
        [typeof(MagicGemVoid)] = typeof(ProjectionMagicGemVoid),
        [typeof(MagicGemWater)] = typeof(ProjectionMagicGemWater),
        [typeof(MagicGemWind)] = typeof(ProjectionMagicGemWind),
        [typeof(ManaBurst)] = typeof(ProjectionManaBurst),
        [typeof(MoralApproval)] = typeof(ProjectionMoralApproval),
        [typeof(OpenLock)] = typeof(ProjectionOpenLock),
        [typeof(PassTheParcel)] = typeof(ProjectionPassTheParcel),
        [typeof(PerfectProjector)] = typeof(ProjectionPerfectProjector),
        [typeof(ProjectionBegin)] = typeof(ProjectionProjectionBegin),
        [typeof(RejuvenationSpecial)] = typeof(ProjectionRejuvenationSpecial),
        [typeof(ReturnToEarth)] = typeof(ProjectionReturnToEarth),
        [typeof(RinDefend)] = typeof(ProjectionRinDefend),
        [typeof(RinStrike)] = typeof(ProjectionRinStrike),
        [typeof(RinsPendantPioneer)] = typeof(ProjectionRinsPendantPioneer),
        [typeof(RinsPendantProjection)] = typeof(ProjectionRinsPendantProjection),
        [typeof(RinsPendantSword)] = typeof(ProjectionRinsPendantSword),
        [typeof(RinsPendantTreasure)] = typeof(ProjectionRinsPendantTreasure),
        [typeof(RuleBreaker)] = typeof(ProjectionRuleBreaker),
        [typeof(SimpleTrial)] = typeof(ProjectionSimpleTrial),
        [typeof(SuppressionTactic)] = typeof(ProjectionSuppressionTactic),
        [typeof(TrueEye)] = typeof(ProjectionTrueEye),
        [typeof(WantedPoster)] = typeof(ProjectionWantedPoster),
        [typeof(WhyAreYouHere)] = typeof(ProjectionWhyAreYouHere),
    };

    /// <summary>Projection type for an original card, or the generic 伪卡牌 fallback.</summary>
    public static Type GetProjectionType(Type originalType) =>
        _map.TryGetValue(originalType, out Type? t) ? t : typeof(GenericProjectionCard);
}
