using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）LawAka — projection (weakened) copy of LawAka.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionLawAka : ProjectionCardBase
{
    public ProjectionLawAka() : base(CardType.Skill, CardRarity.Uncommon, TargetType.Self) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        new BlockVar(10m, ValueProp.Move)
    };
    public override string PortraitPath => "LawAka.png".CardPortraitPath();
    public override string CustomPortraitPath => "LawAka.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "LawAka.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        // Flat block — no reflect power is granted.
        await CreatureCmd.GainBlock(Owner.Creature, base.DynamicVars.Block, null);
    }
    protected override void OnUpgrade()
    {
    }
}
