using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）MagicGemVoid — projection (weakened) copy of MagicGemVoid.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionMagicGemVoid : ProjectionCardBase
{
    public ProjectionMagicGemVoid() : base(CardType.Attack, CardRarity.Common, TargetType.AllEnemies) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        new DamageVar(2m, ValueProp.Move)
    };
    public override string PortraitPath => "MagicGemVoid.png".CardPortraitPath();
    public override string CustomPortraitPath => "MagicGemVoid.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "MagicGemVoid.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
            .FromCard(this)
            .TargetingAllOpponents(base.CombatState!)
            .Execute(choiceContext);
    }
    protected override void OnUpgrade()
    {
    }
}
