using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）AhaMirror — projection (weakened) copy of AhaMirror.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionAhaMirror : ProjectionCardBase
{
    public ProjectionAhaMirror() : base(CardType.Skill, CardRarity.Uncommon, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
    };
    public override string PortraitPath => "AhaMirror.png".CardPortraitPath();
    public override string CustomPortraitPath => "AhaMirror.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "AhaMirror.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        if (CombatState == null) return;

        // Only stun in normal monster rooms, not Elite or Boss
        var roomType = CombatState.RunState.CurrentRoom.RoomType;
        if (roomType == RoomType.Elite || roomType == RoomType.Boss) return;

        foreach (var enemy in CombatState.HittableEnemies)
            await CreatureCmd.Stun(enemy);
    }
    protected override void OnUpgrade()
    {
    }
}
