using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）RinsPendantPioneer — projection (weakened) copy of RinsPendantPioneer.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionRinsPendantPioneer : ProjectionCardBase
{
    public ProjectionRinsPendantPioneer() : base(CardType.Skill, CardRarity.Rare, TargetType.None) { }

    // 阿哈打击！ referenced in the description — show a card preview on hover.
    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
        new[] { HoverTipFactory.FromCard<AhaStrike>() };

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "RinsPendantPioneer.png".CardPortraitPath();
    public override string CustomPortraitPath => "RinsPendantPioneer.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "RinsPendantPioneer.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        if (Owner == null || CombatState == null) return;
        // Directly creates 1 Exhausting AhaStrike.
        var strike = CombatState.CreateCard<AhaStrike>(Owner);
        strike.AddKeyword(CardKeyword.Exhaust);
        await CardPileCmd.AddGeneratedCardToCombat(strike, PileType.Hand, Owner);
    }
    protected override void OnUpgrade() { }
}
