using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）EpicClayTablet — projection (weakened) copy of EpicClayTablet.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionEpicClayTablet : ProjectionCardBase
{
    public ProjectionEpicClayTablet() : base(CardType.Skill, CardRarity.Uncommon, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        // No canonical vars
    };
    public override string PortraitPath => "EpicClayTablet.png".CardPortraitPath();
    public override string CustomPortraitPath => "EpicClayTablet.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "EpicClayTablet.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await CardPileCmd.Draw(choiceContext, 1m, Owner, false);
    }
    protected override void OnUpgrade()
    {
    }
}
