using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Powers;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）AhaSword — projection (weakened) copy of AhaSword.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionAhaSword : ProjectionCardBase
{
    public ProjectionAhaSword() : base(CardType.Attack, CardRarity.Rare, TargetType.AllEnemies) { }

    // 阿哈打击！ referenced in the description — show a card preview on hover.
    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
        new[] { HoverTipFactory.FromCard<AhaStrike>() };

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        new DamageVar(2m, ValueProp.Move)
    };
    public override string PortraitPath => "AhaSword.png".CardPortraitPath();
    public override string CustomPortraitPath => "AhaSword.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "AhaSword.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
            .FromCard(this)
            .TargetingAllOpponents(base.CombatState!)
            .Execute(choiceContext);

        // Direct +1 AhaStrike damage this combat — no counter is set up.
        await PowerCmd.Apply<PowerAhaStrikeDamageUp>(choiceContext, Owner.Creature, 1m, Owner.Creature, this);
    }
    protected override void OnUpgrade()
    {
    }
}
