using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）RejuvenationSpecial — projection (weakened) copy of RejuvenationSpecial.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionRejuvenationSpecial : ProjectionCardBase
{
    public ProjectionRejuvenationSpecial() : base(CardType.Power, CardRarity.Rare, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        // No canonical vars
    };
    public override string PortraitPath => "RejuvenationSpecial.png".CardPortraitPath();
    public override string CustomPortraitPath => "RejuvenationSpecial.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "RejuvenationSpecial.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        // Next turn, gain 2 Energy (instead of an extra turn).
        await PowerCmd.Apply<FateNightOfTheGalacticRailway.Core.Powers.NextTurnEnergyPower>(choiceContext, Owner.Creature, 2m, Owner.Creature, this);
    }
    protected override void OnUpgrade()
    {
    }
}
