using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）PerfectProjector — projection (weakened) copy of PerfectProjector.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionPerfectProjector : ProjectionCardBase
{
    public ProjectionPerfectProjector() : base(CardType.Skill, CardRarity.Uncommon, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "PerfectProjector.png".CardPortraitPath();
    public override string CustomPortraitPath => "PerfectProjector.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "PerfectProjector.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        if (Owner == null || CombatState == null) return;

        var prev = CombatManager.Instance.History.CardPlaysFinished
            .LastOrDefault(e => e.CardPlay.Card.Owner == Owner
                             && e.CardPlay.Card != this
                             && e.HappenedThisTurn(CombatState));
        if (prev == null) return;

        var prevCard = prev.CardPlay.Card;
        CardModel dupe;
        if (prevCard is ProjectionCardBase)
        {
            // Previous card is already a projection — copy its effect directly.
            dupe = prevCard.CreateDupe();
        }
        else
        {
            // Copy the projection version of the original card's effect.
            dupe = ProjectionUtil.CreateProjectionCard(prevCard, CombatState, Owner);
        }

        await CardCmd.AutoPlay(choiceContext, dupe, null);
    }
    protected override void OnUpgrade() { }
}
