using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Powers;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）RuleBreaker — projection (weakened) copy of RuleBreaker.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionRuleBreaker : ProjectionCardBase
{
    public ProjectionRuleBreaker() : base(CardType.Attack, CardRarity.Rare, TargetType.AnyEnemy) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        new DamageVar(4m, ValueProp.Move)
    };
    public override string PortraitPath => "RuleBreaker.png".CardPortraitPath();
    public override string CustomPortraitPath => "RuleBreaker.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "RuleBreaker.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        ArgumentNullException.ThrowIfNull(cardPlay.Target, nameof(cardPlay.Target));
        await DamageCmd.Attack(base.DynamicVars.Damage.BaseValue)
            .FromCard(this)
            .Targeting(cardPlay.Target)
            .Execute(choiceContext);

        await PowerCmd.Apply<RuleBreakerMark>(choiceContext, cardPlay.Target, 1m, Owner.Creature, this);
    }
    protected override void OnUpgrade()
    {
    }
}
