using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Potions;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）KingWine — projection (weakened) copy of KingWine.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionKingWine : ProjectionCardBase
{
    public ProjectionKingWine() : base(CardType.Skill, CardRarity.Uncommon, TargetType.None) { }

    private static readonly Type[] GemPotions =
    {
        typeof(EnergyGemPotion),
        typeof(PioneerGemPotion),
        typeof(TreasureGemPotion),
        typeof(ProjectionGemPotion),
        typeof(ExcaliburGemPotion),
    };
    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "KingWine.png".CardPortraitPath();
    public override string CustomPortraitPath => "KingWine.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "KingWine.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        if (Owner == null) return;
        var rng = Owner.RunState.Rng.CombatPotionGeneration;
        var type = GemPotions[rng.NextInt(GemPotions.Length)];
        PotionModel potion;
        if (type == typeof(EnergyGemPotion)) potion = ModelDb.Potion<EnergyGemPotion>().ToMutable();
        else if (type == typeof(PioneerGemPotion)) potion = ModelDb.Potion<PioneerGemPotion>().ToMutable();
        else if (type == typeof(TreasureGemPotion)) potion = ModelDb.Potion<TreasureGemPotion>().ToMutable();
        else if (type == typeof(ProjectionGemPotion)) potion = ModelDb.Potion<ProjectionGemPotion>().ToMutable();
        else potion = ModelDb.Potion<ExcaliburGemPotion>().ToMutable();

        await PotionCmd.TryToProcure(potion, Owner);
    }
    protected override void OnUpgrade() { }
}
