using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Powers;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）RinsPendantSword — projection (weakened) copy of RinsPendantSword.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionRinsPendantSword : ProjectionCardBase
{
    public ProjectionRinsPendantSword() : base(CardType.Skill, CardRarity.Rare, TargetType.None) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "RinsPendantSword.png".CardPortraitPath();
    public override string CustomPortraitPath => "RinsPendantSword.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "RinsPendantSword.png".CardPortraitPath();
    private decimal _freeCount = 3m;
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await PowerCmd.Apply<NextGoldenSlashFreePower>(
            choiceContext, Owner.Creature, _freeCount, Owner.Creature, this);
    }
    protected override void OnUpgrade()
    {
        _freeCount = 4m;
    }
}
