using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Combat;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）MoralApproval — projection (weakened) copy of MoralApproval.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionMoralApproval : ProjectionCardBase
{
    public ProjectionMoralApproval() : base(CardType.Skill, CardRarity.Uncommon, TargetType.Self) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        // No canonical vars
    };
    public override string PortraitPath => "MoralApproval.png".CardPortraitPath();
    public override string CustomPortraitPath => "MoralApproval.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "MoralApproval.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        await PowerCmd.Apply<MegaCrit.Sts2.Core.Models.Powers.StrengthPower>(choiceContext, Owner.Creature, 1m, Owner.Creature, this);
    }

    // This-turn only: remove the strength layer this projection added at end of the player's turn.
    public override async Task AfterSideTurnEnd(PlayerChoiceContext choiceContext, CombatSide side, IEnumerable<Creature> participants)
    {
        await base.AfterSideTurnEnd(choiceContext, side, participants);
        if (Owner == null || !participants.Contains(Owner.Creature)) return;
        var power = Owner.Creature.GetPower<MegaCrit.Sts2.Core.Models.Powers.StrengthPower>();
        if (power != null)
            await PowerCmd.ModifyAmount(choiceContext, power, -1m, Owner.Creature, null);
    }

    protected override void OnUpgrade()
    {
    }
}
