using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）AhaMirror — projection (weakened) copy of AhaMirror.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionAhaMirror : ProjectionCardBase
{
    public ProjectionAhaMirror() : base(CardType.Skill, CardRarity.Uncommon, TargetType.AnyEnemy) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
    };
    public override string PortraitPath => "AhaMirror.png".CardPortraitPath();
    public override string CustomPortraitPath => "AhaMirror.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "AhaMirror.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        if (cardPlay.Target == null || CombatState == null) return;

        // In Elite/Boss rooms only summoned minions can be selected — the initial
        // encounter monsters (the elite/boss itself) are immune.
        var roomType = CombatState.RunState.CurrentRoom.RoomType;
        bool eliteOrBossRoom = roomType == RoomType.Elite || roomType == RoomType.Boss;
        if (eliteOrBossRoom && IsInitialEncounterMonster(cardPlay.Target))
            return;

        await CreatureCmd.Stun(cardPlay.Target);
    }

    /// <summary>Whether <paramref name="enemy"/> is one of the encounter's initial
    /// monsters (as opposed to a summon that spawned mid-combat).</summary>
    private static bool IsInitialEncounterMonster(Creature enemy)
    {
        var encounter = enemy.CombatState?.Encounter;
        return encounter?.MonstersWithSlots.Any(ms => ms.Item1.Creature == enemy) == true;
    }

    protected override void OnUpgrade()
    {
    }
}
