using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）SuppressionTactic — projection (weakened) copy of SuppressionTactic.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionSuppressionTactic : ProjectionCardBase
{
    public ProjectionSuppressionTactic() : base(CardType.Attack, CardRarity.Common, TargetType.AllEnemies) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
    };
    public override string PortraitPath => "SuppressionTactic.png".CardPortraitPath();
    public override string CustomPortraitPath => "SuppressionTactic.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "SuppressionTactic.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        // No damage — only applies 1 Weak to all enemies.
        var state = base.CombatState!;
        foreach (var enemy in state.HittableEnemies)
            await PowerCmd.Apply<WeakPower>(choiceContext, enemy, 1m, Owner.Creature, this);
    }
    protected override void OnUpgrade()
    {
    }
}
