using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）WantedPoster — projection (weakened) copy of WantedPoster.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionWantedPoster : ProjectionCardBase
{
    public ProjectionWantedPoster() : base(CardType.Skill, CardRarity.Uncommon, TargetType.AnyEnemy) { }

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[] { };
    public override string PortraitPath => "WantedPoster.png".CardPortraitPath();
    public override string CustomPortraitPath => "WantedPoster.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "WantedPoster.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        ArgumentNullException.ThrowIfNull(cardPlay.Target);
        // Applies 1 Vulnerable — no card draw.
        await PowerCmd.Apply<MegaCrit.Sts2.Core.Models.Powers.VulnerablePower>(choiceContext, cardPlay.Target, 1m, Owner.Creature, this);
    }
    protected override void OnUpgrade()
    {
    }
}
