using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.ValueProps;
using FateNightOfTheGalacticRailway.Core.Characters;
using FateNightOfTheGalacticRailway.Core.Cards;

namespace FateNightOfTheGalacticRailway.Core.Cards.Projection;

// This file is auto-generated by scripts/generate_projections.py.
/// <summary>（伪）GoldenRule — projection (weakened) copy of GoldenRule.</summary>
[Pool(typeof(WeakenedCardPool))]
public class ProjectionGoldenRule : ProjectionCardBase
{
    public ProjectionGoldenRule() : base(CardType.Skill, CardRarity.Common, TargetType.None) { }

    // 王之财宝！ referenced in the description — show a card preview on hover.
    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
        new[] { HoverTipFactory.FromCard<KingTreasure>() };

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        // No canonical vars
    };
    public override string PortraitPath => "GoldenRule.png".CardPortraitPath();
    public override string CustomPortraitPath => "GoldenRule.png".BigCardPortraitPath();
    public override string BetaPortraitPath => "GoldenRule.png".CardPortraitPath();
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        if (Owner == null) return;
        // Directly creates 1 King's Treasure — no persistent power is granted.
        await KingTreasure.AddToHand(Owner);
    }
    protected override void OnUpgrade()
    {
    }
}
